import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    domains: [
      "5.imimg.com",
      "automaticlaundry.com",
      "blog.sfapp.magefan.top",
      "blog.wonderchef.com",
      "cdn.thewirecutter.com",
      "c8.alamy.com",
      "hips.hearstapps.com",
      "img.freepik.com",
      "images.herzindagi.info",
      "images.squarespace-cdn.com",
      "i.ytimg.com",
      "media.istockphoto.com",
      "newtackserviceplatform.com",
      "omsaimaintenance.com",
      "os-wordpress-media.s3.ap-south-1.amazonaws.com",
      "plus.unsplash.com",
      "roservice.center",
      "sunkitchenchimneyservice.com",
      "sp-ao.shortpixel.ai",
      "starappliancerepaircc.com",
      "storage.beko.co.uk",
      "sparkenterprisesolution.in",
      "www.asap-appliance-repair.com",
      "www.glotechrepairs.co.uk",
      "www.inventiva.co.in",
      "images-cdn.ubuy.co.in",
      "www.kent.co.in",
      "www.liljegrenlaw.com",
      "t4.ftcdn.net",
      "www.livemint.com",
      "www.freepurity.com",
      "www.shutterstock.com",
      "trustworthyhomeservices.in",
      "randomuser.me",
      "images.unsplash.com",
      "cdn-icons-png.freepik.com",
      "cdn-icons-png.flaticon.com",
      "html.kodesolution.com",
      "unicktheme.com",
      "files.yappe.in",
      "handyman.fixherotheme.com",
      "upload.wikimedia.org",
      "marpol.co.uk",
      "www.ciccomputech.com",
      "res.cloudinary.com",
      "media.croma.com",
      "shop.kent.co.in", "images.unsplash.com",
    ],
  },
};

export default nextConfig;
